GestionUsuarios/Controllers/CuentasController.cs
using GestionUsuarios.ViewsModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace GestionUsuarios.Controllers
{
    //[Authorize(Roles ="Administrador")]
    //[Authorize(Roles ="Usuario")]
    public class CuentasController : Controller
    {
        //Administrar y gestionar usuarios
        private readonly UserManager<IdentityUser> gestionUsuarios;
        //Metodos para login
        private readonly SignInManager<IdentityUser> gestionLogin;

        public CuentasController(UserManager<IdentityUser> gestionUsuarios, SignInManager<IdentityUser> gestionLogin)
        {
            this.gestionUsuarios = gestionUsuarios;
            this.gestionLogin = gestionLogin;
        }

        [HttpGet]
        [Route("Cuentas/Registro")]
        [AllowAnonymous]
        public IActionResult Registrar()
        {
            return View();
        }

        [HttpPost]
        [Route("Cuentas/Registro")]
        [AllowAnonymous]
        public async Task<IActionResult> Registro(RegistroModelo model)
        {
            if (ModelState.IsValid)
            {
                var usuario = new IdentityUser
                {
                    UserName = model.Email,
                    Email = model.Email
                };
                var resultado = await gestionUsuarios.CreateAsync(usuario, model.Password);

                if (resultado.Succeeded)
                {
                    await gestionLogin.SignInAsync(usuario, isPersistent: false);
                    return RedirectToAction("Index", "Home");
                }

                foreach (var error in resultado.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(model);           
        }

        [HttpPost]
        [Route("Cuentas/CerrarSesion")]
        public async Task<IActionResult> CerrarSesion()
        {
            await gestionLogin.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("Cuentas/Login")]
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [Route("Cuentas/Login")]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModelo modelo)
        {
            if (ModelState.IsValid)
            {
                var result = await gestionLogin.PasswordSignInAsync(
                    modelo.Email, modelo.Password, modelo.Recuerdame, false);
                
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }

                ModelState.AddModelError(string.Empty, "Inicio de sesion no valido");
            }

            return View(modelo);

        }

    }
}

GestionUsuarios/Views/Cuentas/Login.cshtml
@using GestionUsuarios.ViewsModels
@model LoginViewModelo

@{
    ViewData["Title"] = "Log in";
}


<div class="hold-transition login-page">
    <div class="login-box">
        <div class="card card-outline card-primary">
            <div class="card-header text-center">
                <a class="h1"><b>Login</b></a>
            </div>
            <div class="card-body">
                <p class="login-box-msg">Sign in to start your session</p>
                <form id="account" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="input-group mb-3">
                    <input asp-for="Email" class="form-control" placeholder="Email" aria-required="true" />
                    <div class="input-group-append">
                    <div class="input-group-text">
                        <span class="fas fa-envelope"></span>
                    </div>
                    </div>
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="input-group mb-3">
                <input asp-for="Password" class="form-control" placeholder="Contraseña" aria-required="true" />
                    <div class="input-group-append">
                    <div class="input-group-text">
                        <span class="fas fa-lock"></span>
                    </div>
                    </div>
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                
                <div class="row">
                    <div class="col-8">
                        <div class="checkbox">
                            <label asp-for="Recuerdame" class="form-label">
                            <input class="form-check-input" asp-for="Recuerdame" />
                            @Html.DisplayNameFor(m => m.Recuerdame)
                            </label>
                        </div>
                    </div>
                </div>

                <div>
                    <button id="login-submit" type="submit" class="w-100 btn btn-lg btn-primary">Log in</button>
                </div>
                <div>
                    <p>
                        <a >Olvide la contraseña</a>
                    </p>
                    <p>
                        <a asp-controller="Cuentas" asp-action="Registrar" >Registrar Nuevo Usuario</a>
                    </p>
                </div>
                </form>
            </div>
    
        </div>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GestionUsuarios/Views/Cuentas/Registrar.cshtml
@using GestionUsuarios.ViewsModels
@model RegistroModelo

@{
    ViewData["Title"] = "Register";
}


<div class="hold-transition register-page">
<div class="register-box">
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a class="h1"><b>Registrar</b></a>
    </div>
    <div class="card-body">
        <form id="registerForm" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="input-group mb-3">
                <input asp-for="Email" class="form-control" placeholder="Email" aria-required="true" />
                <div class="input-group-append">
                <div class="input-group-text">
                <span class="fas fa-envelope"></span>
                </div>               
                </div>    
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="input-group mb-3">
                <input asp-for="Password" class="form-control" placeholder="Contraseña" aria-required="true" />
                <div class="input-group-append">
                <div class="input-group-text">
                <span class="fas fa-lock"></span>
                </div>               
                </div>    
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="input-group mb-3">
                <input asp-for="ValidarPassword" class="form-control" placeholder="Repetir Contraseña" aria-required="true" />
                <div class="input-group-append">
                <div class="input-group-text">
                <span class="fas fa-lock"></span>
                </div>               
                </div>    
                <span asp-validation-for="ValidarPassword" class="text-danger"></span>
            </div>         
            <button id="registerSubmit" type="submit" class="w-100 btn btn-lg btn-primary">Registrar</button>
        </form>
        </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->

</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}